name: Daily Commit

on:
  schedule:
    - cron: '50 16 * * *'  # Runs at 12:30 UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  create-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create empty commit
        run: |
          git commit --allow-empty -m "Daily automated commit"
          git push

      - name: "23f2003807@ds.study.iitm.ac.in"
        run: echo "This step includes the specified email address"
