name: Echo Email 

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: xxxxx@ds.study.iitm.ac.in
        run: echo "Hello, world!"